apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
  name: user-service
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: user
  type: NodePort