apiVersion: v1
kind: Service
metadata:
  labels:
    app: userdetail
  name: userdetail-service
  namespace: default
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: userdetail
  type: ClusterIP